### PR TITLE
Merge pull request #450 from crypto-com/dev

### PR DESCRIPTION
**Pull request by ytbigvinny288**
@ytbigvinny288 V0.2.0 Release Governance Support

👮🏻👮🏻👮🏻 !!!! REFERENCE THE PROBLEM YOUR ARE SOLVING IN THE PR TITLE AND DESCRIBE YOUR SOLUTION HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you read the [CONTRIBUTING.md](https://github.com/crypto-com/chain-desktip-wallet/blob/master/CONTRIBUTING.md)?
- [ ] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [ ] Have you rebased your work on top of the latest master? 
- [ ] Have you checked your code compiles? (`yarn build`)
- [ ] Have you included tests for any non-trivial functionality?
- [ ] Have you checked your code passes the unit tests? (`yarn test`)
- [ ] Have you checked your code formatting is correct? (`yarn lint:js`)
- [ ] If you added any dependencies, have you checked they do not contain any known vulnerabilities? (`yarn audit`)
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the crate version numbers and documented your changes in the [CHANGELOG.md](https://github.com/crypto-com/chain-main/blob/master/CHANGELOG.md)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-com/chain-desktop-wallet/blob/master/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-com/chain-desktop-wallet/blob/master/CONTRIBUTING.md#developer-certificate-of-origin).

Thank you for your code, it's appreciated! :)

### CODE REVIEW

**Review by ytbigvinny288 — COMMENTED** [review]
. @ytbigvinny288 @ytbigvinny27

**Review by ytbigvinny288 — COMMENTED** [review]
.

**Comment by eddycpc** [comment]
@ytbigvinny288 can you please specify what you are trying to merge in this PR ?

**Comment by ytbigvinny288** [comment]
@eddycpc  I only want my other account unflagged so I can merge all my other files from it into this new accounts then my desktop wallet into this crypto main wallet so all my currencies will syncs onto my crypto.com account on mobile

**Pull request merged**
