### PR TITLE
feat: Add memo field to Address Book

### LINKED ISSUE #844: Critical Enhancement Request:  Add memo field to Address Book for Crypto.com Android App Transfers of CRO!!
**Is your feature request related to a problem? Please describe.**

Your address book lacks an essential field - a Memo field.  As you almost certainly know (or should know), the Crypto.com Android App cannot receive a CRO deposit, without the right Memo #!  As the Address Book is now, I have added this address, but it opens me open to the possibility of forgetting the need to manually add the Memo #, which could be disastrous ...

**Describe the solution you'd like**

There needs to be a an additional optional Memo field added to the records stored in your wallet's Address Book.

**Describe alternatives you've considered**

The only alternative is to simply not store this particular (often used!) address in the Address Book at all, to avoid the potential of thinking I can simply click on the Address and carry on, forgetting this essential piece of info is missing!

**Additional context**

### PR DESCRIPTION
**Pull request by XinyuCRO**
Close #844

### CODE REVIEW

**Comment by crypto-matto** [comment]
Revised on `allowClear` layout
Screenshot 2021-12-02 at 12 32 39 PM

**Review by crypto-matto — CHANGES_REQUESTED** [review]
@XinyuCRO Please also add `Memo` field in `Settings` => `Address Book`

**Comment by XinyuCRO** [comment]
image

**Review by crypto-matto — APPROVED** [review]
LGTM

**Pull request merged**
