### PR TITLE
Problem: Support Crc20 token data

### PR DESCRIPTION
**Pull request by cdc-Hitesh**
Added new support to `CronosIndexingAPi`:

```
// - Token transfers event logs by address
  //?module=account&action=tokentx&address={addressHash}
  getTokenTransfersByAddress(
    address: string,
    options?: tokenTransfersRequestOptions,
  ): Promise<TokenTransferEventLogsResponse>;

  // Returns a list of tokens owned by an address
  // ?module=account&action=tokenlist&address={addressHash}
  getTokensOwnedByAddress(address: string): Promise<TokensOwnedByAddressResponse>;

  // Get ERC-20 or ERC-721 token by contract address.
  // ?module=token&action=getToken&contractaddress={contractAddressHash}
  getContractDataByAddress(contractAddress: string): Promise<ContractDataResponse>;
```

### CODE REVIEW

**Review by crypto-eddy — COMMENTED** [review]
Is there way to get a token icon url from the available APIs ?

**Comment by cdc-Hitesh** [comment]
> Is there way to get a token icon url from the available APIs ?

I will have to check for this one.

**Comment by crypto-matto** [comment]
> > Is there way to get a token icon url from the available APIs ?
> 
> I will have to check for this one.

Is there any updates on this?

**Comment by cdc-Hitesh** [comment]
> > > Is there way to get a token icon url from the available APIs ?
> > 
> > 
> > I will have to check for this one.
> 
> Is there any updates on this?

Yes, I found a solution but it is an authenticated endpoint.

Either we create a new backend or host a manually downloaded image?

What you say?

**Comment by crypto-matto** [comment]
> > > > Is there way to get a token icon url from the available APIs ?
> > > 
> > > 
> > > I will have to check for this one.
> > 
> > 
> > Is there any updates on this?
> 
> Yes, I found a solution but it is an authenticated endpoint.
> 
> Either we create a new backend or host a manually downloaded image?
> 
> What you say?

While our current CRO images are hosted manually, I think it is not feasible to do that for all the coins in the future. I'd suggest to create a new backend.

**Review by crypto-matto — APPROVED** [review]
LGTM. A separate PR shall be created for the icon_url support from a to-be-implemented backend

**Pull request merged**
