### PR TITLE
Remove extra text

### PR DESCRIPTION
**Pull request by eddycpc**

### CODE REVIEW

**Review by crypto-matto — COMMENTED** [review]
```
{`${currentSession.wallet.config.network.coin.croDenom}...`}
```
This one not work? 
what about 
```
{`${currentSession.getBaseDenomination().toLowerCase()}...`}
```

**Comment by eddycpc** [comment]
> ```
> {`${currentSession.wallet.config.network.coin.croDenom}...`}
> ```
> 
> This one not work?
> what about
> 
> ```
> {`${currentSession.getBaseDenomination().toLowerCase()}...`}
> ```

It worked but it was technically not necessary lol 

The text placeholder was being used in other address inputs

**Review by leejw51crypto — APPROVED** [review]
lgtm

**Review by grandmastergainz — APPROVED** [review]

**Review by grandmastergainz — APPROVED** [review]

**Review by crypto-matto — APPROVED** [review]

**Review by grandmastergainz — COMMENTED** [review]
M

**Pull request merged**
