### PR TITLE
Ethereum Integration

### PR DESCRIPTION
**Pull request by crypto-eddy**
## Ethereum Chain
- [x] Handle new static ETH asset creation.
- [x] Load new ETH asset balance
  - Indexing Endpoint: https://eth-indexing.crypto.org/ethereum/mainnet/api/v1/address/0x2992b824ed06a99d0816d39c77e9512424253efc/balance
- [x] Support transferring new ETH asset. 
  - Node RPC Endpoint: https://eth-indexing.crypto.org/ethereum/mainnet/rpc 
- [x] Support for Ledger.
- Indexing service on Transaction History is still not updated to latest block. Direct users to Etherscan instead. 

## Screenshots
Screen Shot 2022-01-06 at 11 00 32 AM
Screen Shot 2022-01-06 at 11 05 37 AM
螢幕截圖 2022-08-03 下午6 05 16

## Other Outstanding supported Features
- #1032 
- #1167 
- #1209

### CODE REVIEW

**Comment by crypto-matto** [comment]
## Issue
- [ ] Tooltip incorrect

- [ ] Ethereum price is not retrieved correctly

**Comment by crypto-matto** [comment]
## Issue
- [ ] Tooltip incorrect

- [ ] Ethereum price is not retrieved correctly

**Comment by crypto-matto** [comment]
## Issue
- [ ] Ethereum address is different from Cronos Beta in Ledger Wallet Creation

**Comment by crypto-matto** [comment]
## Issue
- [ ] Ethereum address is different from Cronos Beta in Ledger Wallet Creation

**Comment by crypto-matto** [comment]
## Current status of Indexing API

### Testnet (Rinkeby):
:white_check_mark: **GET** /address/{addr}/balance
:white_check_mark: **GET** /address/{addr}/info
:x: **GET** /address/{addr}/transaction-history
:white_check_mark: **GET** /network-info
:white_check_mark: **POST** /rpc?apikey={{apikey}}


### Mainnet API endpoint:
:white_check_mark: **GET** /address/{addr}/balance
:x: **GET** /address/{addr}/transaction-history
:x: **POST** /rpc?apikey={{apikey}}

**Comment by crypto-matto** [comment]
## Missing token icons for ERC20 tokens
Came across with this [trustwallet/assets](https://github.com/trustwallet/assets) github repo, which seems able to get what we need.

https://github.com/trustwallet/assets/tree/master/blockchains/ethereum
All token logos are following the path blockchains/ethereum/assets/{token_contract_address}/logo.png

Therefore, we may access the icon with, e.g. https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x0000000000085d4780B73119b644AE5ecd22b376/logo.png

**Comment by crypto-matto** [comment]
## Task 
- [ ] Suggested by Price API team, we'd better prepare a ERC20 token whitelist to fetch market price properly

**Review by crypto-matto — APPROVED** [review]

**Review by XinyuCRO — APPROVED** [review]

**Review by crypto-matto — APPROVED** [review]

**Pull request merged**
