### PR TITLE
Problem (Fix #369) : Load validator set with more props data and persist in the local DB store

### LINKED ISSUE #369: Problem : Load validator set with more props data  and persist in the local DB store

### PR DESCRIPTION
**Pull request by crypto-matto**
螢幕截圖 2021-03-31 下午6 17 31

### CODE REVIEW

**Comment by eddycpc** [comment]
A few observations :

- The pop up seems to have a lot of white empty space around
- We can probably show 5 validators in the first view instead of 3
- The validator website looks empty in the table.
- We can use a middle ellipsis for validator address to save some width

**Review by jzitro88 — DISMISSED** [review]

**Comment by crypto-matto** [comment]
螢幕截圖 2021-03-31 下午8 33 50

**Comment by eddycpc** [comment]
You might maybe display the commission rate in percentage %

**Comment by chewy917** [comment]
0x00009999219ab540356cBB839Cbe0530d770Fa 
0x00009999219ab540356cBB839Cbe0530d770Fa

**Review by chewy917 — COMMENTED** [review]
380b73454671cfd28426eda6904a5a36

**Review by eddycpc — APPROVED** [review]

**Comment by anthony-kenikh** [comment]
Why missing some validators?
At [crypto.org](https://crypto.org/explorer/validators) I see different top list

**Comment by crypto-matto** [comment]
@anthony-kenikh We are showing more validators & infos now #387

**Pull request merged**
