### PR TITLE
feat: Support EVM chains switch in DApp Browser

### PR DESCRIPTION
**Pull request by XinyuCRO**
Add add/switch EVM compatible support for DApp Browser.

## Things to notice
- Add support for `wallet_addEthereumChain` and `wallet_switchEthereumChain` Ethereum RPC methods, which mean we can handle  add/switch chain request  from DApps, eg. [Chainlist](https://chainlist.org/)
- Add a new section in DApp Browser to manage chain configs
- Add support for the fee market EIP-1559 implementation in every EVM chain transaction inside DApp Browser (we should support this for other operations in wallet later, since testnet has already got the fee market feature online)
- Change the user agent in DApp Browser back to the normal one(instead of faking to be a mobile device). 
	- the reason is because some DApps like UniSwap's connect wallet modal shows nothing when the environment is mobile, so we have to remove the useragent hack to make these websites to work. 
	- the side effect of removing this can cause some website's auto-connecting not work, but if user connect it by hand once, it will work as usual later.

## Screenshoots
- chain switch in addressBar
image

- chain config tab for users to manage chains
image

- Add/Switch chain request modal

<div>
image
image
</div>

- Confirm Tx drawer will show different currency symbol when using other chains
image

### CODE REVIEW

**Comment by crypto-matto** [comment]
## Issues
- The `Remove` button on newly added chains is not clickable until some actions are done (unknown to me)
- May just hide `Remove` button for Cronos Mainnet & Cronos Testnet

**Comment by XinyuCRO** [comment]
@crypto-matto 

>  The Remove button on newly added chains is not clickable until some actions are done (unknown criteria to me)
yeah, can not remove the chain if it is currently being used

>  Network, after approval, isn't switched on web frontend until wallet disconnect & reconnect manually
Which DApp particular? I tested with top DApps in cronos ranks page, they all works fine

**Comment by crypto-matto** [comment]
> 



> @crypto-matto

> > Network, after approval, isn't switched on web frontend until wallet disconnect & reconnect manually
> 
> Which DApp particular? I tested with top DApps in cronos ranks page, they all works fine
> 
Pancake swap for instance. https://pancakeswap.finance/

**Comment by crypto-matto** [comment]
> 



> @crypto-matto

> > Network, after approval, isn't switched on web frontend until wallet disconnect & reconnect manually
> 
> Which DApp particular? I tested with top DApps in cronos ranks page, they all works fine
> 
Pancake swap for instance. https://pancakeswap.finance/

**Comment by XinyuCRO** [comment]
Will be merged with #912

**Pull request closed without merging**
