### PR TITLE
Internal Release v1.4.2

### PR DESCRIPTION
**Pull request by crypto-matto**
### Additions
- Security enhancement & package dependencies bump
### Bug Fixes
- Potential app crash on Assets Page

### CODE REVIEW

**Comment by Nnelson3222** [comment]
**[]()**

**Comment by Nnelson3222** [comment]
[👍]()

**Review by XinyuCRO — APPROVED** [review]
LGTM

**Comment by Nnelson3222** [comment]
TySent from my iPhoneOn Jul 19, 2023, at 5:24 AM, crypto-matto ***@***.***> wrote:﻿
Merged #1370 into master.

**Review by ap501boi — COMMENTED** [review]
R[](https://github.com/crypto-com/chain-desktop-wallet/pull/1370/files)

**Pull request merged**
