### PR TITLE
Problem: missing `sender address` in confirm txpages (fix #270)

### LINKED ISSUE #270: Problem: missing `sender address` in confirm txpages
add sender address field

### PR DESCRIPTION
**Pull request by leejw51crypto**
Solution: add sender address

### CODE REVIEW

**Comment by eddycpc** [comment]
Screenshots seem to be missing since this is a UI/UX PR

**Comment by crypto-matto** [comment]
螢幕截圖 2021-02-24 下午1 59 48

**Comment by leejw51crypto** [comment]
oh, my bad,
I'll upload now

**Comment by crypto-matto** [comment]
> oh, my bad,
> I'll upload now

I can't perform any transactions (May be it's some problem on my side), so I cannot see the unstake process

**Comment by leejw51crypto** [comment]
withdraw reward
image

stake
image

undelegate
image

**Review by eddycpc — APPROVED** [review]
Good !

**Review by crypto-matto — APPROVED** [review]

**Pull request merged**
