### PR TITLE
Problem (Fix #410) : UI for proposal voting support

### LINKED ISSUE #410: Problem : UI for proposal voting support

### PR DESCRIPTION
**Pull request by crypto-matto**
螢幕截圖 2021-04-14 下午11 37 49
螢幕截圖 2021-04-14 下午11 37 55
螢幕截圖 2021-04-14 下午11 38 02
螢幕截圖 2021-04-14 下午11 38 09

### CODE REVIEW

**Comment by crypto-matto** [comment]
Support `\n` in description
螢幕截圖 2021-04-15 下午2 12 14

**Comment by crypto-matto** [comment]
Updated UI from several feedbacks
螢幕截圖 2021-04-15 下午6 44 00

**Comment by crypto-matto** [comment]
Changed Proposal view from modal to normal content
螢幕截圖 2021-04-16 下午6 40 49

**Comment by eddycpc** [comment]
Loading latest tally on votes that are happening in real time
Screen Shot 2021-04-17 at 10 32 15 AM


Screen Shot 2021-04-17 at 10 31 53 AM

**Pull request merged**
